version: "3.7"

services:
  app_php:
    build:
      context: .
      dockerfile: ./php/Dockerfile
      args:
        - "XDEBUG_MODE=false"
    volumes:
      - "./../:/var/www/html"
      - "./php/php.dev.ini:/usr/local/etc/php/custom.d/php.ini"

  app_db:
    image: mysql:5.7
    cap_add:
      - SYS_NICE
    restart: always
    environment:
      MYSQL_DATABASE: "app_db"
      MYSQL_USER: "app_user"
      MYSQL_PASSWORD: "app_pass"
      MYSQL_ROOT_PASSWORD: "root"
    volumes:
      - "./mysql/my.cnf:/etc/mysql/conf.d/my.cnf"
    ports:
      - "3311:3306"

  app_nginx:
    image: nginx:1.17
    ports:
      - "8888:80"
    volumes:
      - "./../:/var/www/html"
      - "./nginx/log:/var/www/log"
      - "./nginx/site.conf:/etc/nginx/conf.d/default.conf"
    depends_on:
      - app_php
